export const ADD_ORDER = "ADD_ORDER";
export const GET_ORDERS = "GET_ORDERS";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const APPROVE_ORDERS = "APPROVE_ORDERS";
export const OPEN_RETURNED_ORDERS = "OPEN_RETURNED_ORDERS";
export const OPEN_PENDING_ORDERS = "OPEN_PENDING_ORDERS";
export const OPEN_ALL_ORDERS = "OPEN_ALL_ORDERS";

